-- =====================================================================
-- ESQUEMA DE REFERENCIA — ALFA-DEO bot de WhatsApp
-- =====================================================================
-- IMPORTANTE: el esquema REAL se administra directamente en Supabase.
-- Este archivo es SÓLO documentación de lo que el bot consume; el bot
-- NO crea ni migra tablas.
--
-- La migración que agrega el catálogo farmacéutico, las sucursales y los
-- campos de facturación vive en el repo del panel:
--
--     alfadeo-panel/supabase/reunion-catalogo-sucursales.sql
--
-- Se ejecuta una sola vez desde Supabase → SQL Editor. Sin ella, el bot
-- no puede buscar productos ni decir en qué plaza hay existencia.
-- =====================================================================

-- ----------------------- ENUMS (referencia) --------------------------
-- tipo de cliente:      hospital | clinica | farmacia | gobierno | distribuidor | medico | otro
-- canal de solicitud:   incluye 'whatsapp'
-- estado de solicitud:  nueva | en_revision | cotizada | enviada | aceptada | rechazada | facturada | cancelada
-- urgencia:             normal | urgente | programada
-- direccion de mensaje: in | out

-- ----------------------- TABLAS (referencia) -------------------------

-- sucursales: las dos empresas del grupo (minuta 9). GDL es matriz.
-- CREATE TABLE sucursales (
--   id            uuid PRIMARY KEY,
--   clave         text UNIQUE,   -- 'GDL' | 'MTY'
--   nombre        text,
--   razon_social  text,
--   rfc           text,
--   ciudad        text,
--   estado        text,
--   telefono_wa   text,
--   asesor_nombre text,
--   es_matriz     boolean,
--   activo        boolean
-- );

-- productos: catálogo. precio_base es interno y NUNCA se expone al cliente.
-- Las 5 columnas de abajo del bloque las llena el trigger
-- `productos_derivar_nombre` parseando `nombre` (minuta 17).
-- CREATE TABLE productos (
--   id                 uuid PRIMARY KEY,
--   clave              text,
--   nombre             text,       -- "VYLKOR - ONDANSETRON TAB 8 mg C/10"
--   nombre_comercial   text,       -- "VYLKOR"        <- minuta 17
--   nombre_generico    text,       -- "ONDANSETRON"   <- minuta 17
--   concentracion      text,       -- "8 mg"          <- minuta 17
--   forma_farmaceutica text,       -- "TAB"
--   presentacion       text,       -- "C/10"          <- minuta 17, 18
--   codigo_barras      text,       -- de Aspel, para el POS (minuta 22)
--   descripcion        text,
--   laboratorio        text,
--   unidad             text,
--   categoria          text,
--   precio_base        numeric,    -- interno, no exponer
--   tasa_iva           numeric,    -- 0 para medicamento, 0.16 otros (minuta 3)
--   iva_exento         boolean,
--   controlado         boolean,    -- si true => escalar a humano
--   lote               text,       -- minuta 23
--   caducidad          date,
--   activo             boolean
-- );

-- inventario: existencia por plaza (minuta 28).
-- OJO: `ubicacion` es el RACK/LOCKER dentro de la bodega, NO la plaza.
-- CREATE TABLE inventario (
--   id            uuid PRIMARY KEY,
--   producto_id   uuid REFERENCES productos(id),
--   sucursal_id   uuid REFERENCES sucursales(id),   -- <- minuta 28
--   ubicacion     text,                             -- 'RACK N1', 'REFRIGERADO'...
--   existencia    numeric
-- );

-- clientes: upsert por telefono_wa.
-- CREATE TABLE clientes (
--   id                 uuid PRIMARY KEY,
--   nombre             text,
--   empresa            text,
--   tipo               text,        -- enum tipo cliente
--   ciudad             text,
--   telefono_wa        text UNIQUE, -- clave de upsert del bot
--   correo             text,
--   rfc                text,
--   razon_social       text,        -- \
--   regimen_fiscal     text,        --  | datos fiscales, para no volver
--   uso_cfdi           text,        --  | a pedírselos (minuta 1)
--   cp_fiscal          text,        --  |
--   correo_facturacion text,        -- /
--   requiere_factura   boolean,
--   sucursal_id        uuid REFERENCES sucursales(id)
-- );

-- solicitudes:
-- CREATE TABLE solicitudes (
--   id               uuid PRIMARY KEY,
--   folio            int GENERATED ALWAYS AS IDENTITY,  -- lo asigna la BD
--   cliente_id       uuid REFERENCES clientes(id),
--   canal            text,       -- 'whatsapp'
--   estado           text,       -- 'nueva' al crearse
--   urgencia         text,
--   ciudad_entrega   text,
--   responsable      text,
--   requiere_humano  boolean,
--   requiere_factura boolean,    -- <- minuta 1
--   datos_fiscales   jsonb,      -- <- minuta 1
--   sucursal_id      uuid REFERENCES sucursales(id),   -- <- minuta 15
--   notas            text
-- );

-- solicitud_items:
-- CREATE TABLE solicitud_items (
--   id                uuid PRIMARY KEY,
--   solicitud_id      uuid REFERENCES solicitudes(id),
--   producto_id       uuid REFERENCES productos(id),  -- opcional (texto libre)
--   descripcion_libre text,
--   cantidad          numeric,
--   unidad            text,
--   categoria         text,
--   marca             text,
--   presentacion      text,
--   nota              text
-- );

-- conversaciones: estado del bot por número (máquina de estados).
-- CREATE TABLE conversaciones (
--   wa_id                   text PRIMARY KEY,
--   cliente_id              uuid REFERENCES clientes(id),
--   paso                    text,
--   contexto                jsonb,
--   ventana_servicio_expira timestamptz,
--   ultima_actividad        timestamptz
-- );

-- mensajes: log de toda la conversación.
-- CREATE TABLE mensajes (
--   id         uuid PRIMARY KEY,
--   wa_id      text,
--   direccion  text,        -- 'in' | 'out'
--   tipo       text,
--   cuerpo     text,
--   payload    jsonb,
--   created_at timestamptz DEFAULT now()
-- );

-- ----------------------- FUNCIONES QUE USA EL BOT --------------------
-- buscar_productos(q text, limite int)
--   Búsqueda por nombre priorizando el COMERCIAL (minuta 19, 20).
--   Devuelve, por producto, un jsonb `disponibilidad` con la existencia
--   por sucursal (minuta 28).
--
-- parse_producto_nombre(nombre text) -> jsonb
--   Parte "VYLKOR - ONDANSETRON TAB 8 mg C/10" en sus 5 componentes.
