-- =====================================================================
-- Arreglos de esquema que el bot necesita
-- =====================================================================
-- Se corre una vez, como superusuario:
--
--     psql -U postgres -p 5433 -d alfadeo -f sql/arreglos-base.sql
--
-- Es idempotente: correrlo dos veces no hace daño.
--
-- OJO: estas tablas son del esquema COMPARTIDO, que administran las
-- migraciones del panel. Lo que hay aquí debería acabar allá; vive en este
-- repo sólo para que el bot no dependa de que alguien se acuerde.
-- =====================================================================

-- ------------------------------------------------------ mensajes.id ---
-- `mensajes.id` es bigint NOT NULL, pero se quedó SIN identidad y SIN
-- default: la migración a la base local perdió el `generated as identity`
-- que traía el esquema original. Sus tablas hermanas (clientes, solicitudes,
-- solicitud_items) sí tienen `gen_random_uuid()`.
--
-- Sin esto, CADA insert en `mensajes` falla con "null value in column id".
-- Y como registrarMensaje() está escrito para fallar en silencio —el logging
-- nunca debe tumbar una conversación—, el bot seguiría contestando de maravilla
-- mientras el historial completo se pierde. Se descubrió corriendo
-- `npm run probar-base` contra la base de verdad.
--
-- Se usa IDENTITY y no `serial` a propósito: con identidad, Postgres avanza la
-- secuencia por dentro y el rol que inserta NO necesita permisos sobre ella.
-- Con `serial` habría que otorgar USAGE, y eso obligaría a abrirle al bot las
-- secuencias del esquema.
do $$
begin
  if not exists (
    select 1 from pg_attribute
     where attrelid = 'public.mensajes'::regclass
       and attname  = 'id'
       and attidentity in ('a', 'd')      -- 'a' = always, 'd' = by default
  ) then
    alter table mensajes alter column id add generated by default as identity;

    -- La secuencia nace en 1 y ya hay filas: hay que dejarla por encima del
    -- máximo, o el primer mensaje nuevo choca con una llave que ya existe.
    perform setval(
      pg_get_serial_sequence('mensajes', 'id'),
      coalesce((select max(id) from mensajes), 0) + 1,
      false
    );
  end if;
end
$$;

-- Comprobación:
--     select attidentity from pg_attribute
--      where attrelid = 'public.mensajes'::regclass and attname = 'id';
--     -- 'd' = by default, '' = sigue rota

-- --------------------------------------------- clientes.telefono_wa ---
-- El bot identifica al cliente por su número de WhatsApp y lo guarda con
-- INSERT ... ON CONFLICT (telefono_wa). Postgres exige que esa columna tenga
-- una restricción única: sin ella el upsert falla con "no hay restricción
-- única o de exclusión que coincida con la especificación ON CONFLICT".
--
-- La tabla sólo traía la llave primaria sobre `id`. El esquema original sí
-- declaraba `telefono_wa text UNIQUE`; la migración a la base local lo perdió,
-- igual que la identidad de mensajes.id.
--
-- Efecto sin esto: el bot atiende la conversación completa y falla justo al
-- registrar la solicitud. Se descubrió con `npm run simular`.
do $$
begin
  if not exists (
    select 1 from pg_indexes
     where schemaname = 'public'
       and tablename  = 'clientes'
       and indexdef like '%UNIQUE%(telefono_wa)%'
  ) then
    alter table clientes add constraint clientes_telefono_wa_key unique (telefono_wa);
  end if;
end
$$;

-- Comprobación:
--     select indexdef from pg_indexes
--      where tablename = 'clientes' and indexdef like '%telefono_wa%';

-- ------------------------------------------- solicitudes.folio ---
-- Mismo caso que mensajes.id: `folio` es bigint NOT NULL, sin identidad, sin
-- default y sin trigger que lo llene. El bot NO lo envía a propósito —el folio
-- es el número que se le da al cliente y lo tiene que asignar la base, no dos
-- procesos compitiendo— así que el insert fallaba con "null value in column
-- folio".
--
-- No se usa la función `siguiente_folio(p_ambito, p_sucursal_id)` del panel:
-- esa numera documentos del punto de venta por ámbito y sucursal, y nada la
-- conecta con esta tabla. Aquí lo que se perdió en la migración fue la
-- identidad, y eso es lo que se repone.
do $$
begin
  if not exists (
    select 1 from pg_attribute
     where attrelid = 'public.solicitudes'::regclass
       and attname  = 'folio'
       and attidentity in ('a', 'd')
  ) then
    alter table solicitudes alter column folio add generated by default as identity;

    perform setval(
      pg_get_serial_sequence('solicitudes', 'folio'),
      coalesce((select max(folio) from solicitudes), 0) + 1,
      false
    );
  end if;
end
$$;

-- Comprobación:
--     select attidentity from pg_attribute
--      where attrelid = 'public.solicitudes'::regclass and attname = 'folio';
